import type { Product, OutfitCollection } from "../types/product"


export const PRODUCTS_DATA: Product[] = [
  {
    id: "1",
    name: "Camiseta Urban Vibes",
    description: "Camiseta de algodón premium con diseño urbano exclusivo",
    price: 45.99,
    originalPrice: 59.99,
    category: "camisetas",
    brand: "Urban Store",
    images: [
      "https://i.pinimg.com/736x/7b/de/ba/7bdeba12dc862fe2ce95aae1596938d9.jpg",
      "https://i.pinimg.com/736x/14/a5/1a/14a51ac3d873389dcd5dd592456adec0.jpg",
      "https://i.pinimg.com/736x/2d/7c/9a/2d7c9a417c98ba0f76ff677b26b779ba.jpg",
    ],
    colors: ["negro", "blanco", "gris"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    rating: 4.8,
    reviewCount: 124,
    inStock: true,
    isNew: true,
    isBestSeller: false,
    tags: ["algodón", "urbano", "cómodo"],
    createdAt: "2024-01-15",
    isFavorite: false,
  },
  {
    id: "2",
    name: "Sudadera Graffiti Flow",
    description: "Sudadera con capucha y diseño de graffiti auténtico",
    price: 89.99,
    originalPrice: 109.99,
    category: "sudaderas",
    brand: "Street Art Co.",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    colors: ["negro", "gris", "azul"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    rating: 4.6,
    reviewCount: 89,
    inStock: true,
    isNew: false,
    isBestSeller: true,
    tags: ["capucha", "graffiti", "streetwear"],
    createdAt: "2024-01-10",
    isFavorite: true,    // <-- marcada como favorita
  },
  {
    id: "3",
    name: "Zapatillas Street Runner",
    description: "Zapatillas deportivas con diseño urbano y máxima comodidad",
    price: 125.0,
    originalPrice: 149.99,
    category: "zapatillas",
    brand: "Urban Kicks",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    colors: ["blanco", "negro", "gris"],
    sizes: ["38", "39", "40", "41", "42", "43", "44", "45"],
    rating: 4.9,
    reviewCount: 203,
    inStock: true,
    isNew: true,
    isBestSeller: true,
    tags: ["deportivo", "cómodo", "urbano"],
    createdAt: "2024-01-20",
    isFavorite: true,    // <-- marcada como favorita
  },
  {
    id: "4",
    name: "Pantalón City Style",
    description: "Pantalón urbano con corte moderno y detalles únicos",
    price: 67.75,
    originalPrice: 85.0,
    category: "pantalones",
    brand: "City Wear",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    colors: ["negro", "azul", "gris"],
    sizes: ["28", "30", "32", "34", "36", "38"],
    rating: 4.4,
    reviewCount: 67,
    inStock: true,
    isNew: false,
    isBestSeller: false,
    tags: ["moderno", "cómodo", "versátil"],
    createdAt: "2024-01-05",
    isFavorite: false,
  },
  {
    id: "5",
    name: "Gorra Street King",
    description: "Gorra snapback con bordado exclusivo y ajuste perfecto",
    price: 32.5,
    originalPrice: 42.0,
    category: "gorras",
    brand: "King Caps",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    colors: ["negro", "blanco", "rojo"],
    sizes: ["Única"],
    rating: 4.7,
    reviewCount: 156,
    inStock: true,
    isNew: false,
    isBestSeller: true,
    tags: ["snapback", "bordado", "ajustable"],
    createdAt: "2024-01-08",
    isFavorite: false,
  },
  {
    id: "6",
    name: "Reloj Urban Time",
    description: "Reloj digital con diseño futurista y múltiples funciones",
    price: 95.0,
    originalPrice: 120.0,
    category: "accesorios",
    brand: "Tech Time",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    colors: ["negro", "plata", "oro"],
    sizes: ["Única"],
    rating: 4.5,
    reviewCount: 92,
    inStock: true,
    isNew: true,
    isBestSeller: false,
    tags: ["digital", "resistente", "multifunción"],
    createdAt: "2024-01-18",
    isFavorite: false,
  },
];
export const OUTFIT_COLLECTIONS: OutfitCollection[] = [
  {
    id: "street-essentials",
    name: "Street Essentials",
    description: "Lo esencial para tu look urbano diario",
    heroImage:
      "https://i.pinimg.com/1200x/28/52/48/285248308e0ce6658d9728408842c9f0.jpg",
    outfits: [
      {
        id: "outfit-1",
        name: "Urban Classic",
        image: "https://i.pinimg.com/736x/3f/43/90/3f4390f53687b99c819800eb1e894852.jpg",
        totalPrice: 189.99,
        originalPrice: 229.99,
        items: ["Camiseta Urban", "Pantalón Cargo", "Zapatillas Street"],
      },
      {
        id: "outfit-2",
        name: "Street Comfort",
        image: "https://i.pinimg.com/736x/3e/7c/26/3e7c263526ec597612cf4db5de88c89f.jpg",
        totalPrice: 159.99,
        originalPrice: 199.99,
        items: ["Sudadera Básica", "Joggers", "Sneakers"],
      },
      {
        id: "outfit-3",
        name: "Night Vibes",
        image: "https://i.pinimg.com/1200x/34/cc/d7/34ccd7968b83f687f37fb8d9100be6bb.jpg",
        totalPrice: 219.99,
        items: ["Hoodie Premium", "Jeans Slim", "Botas Urban", "Gorra"],
      },
    ],
  },
  {
    id: "premium-collection",
    name: "Premium Collection",
    description: "Piezas exclusivas para ocasiones especiales",
    heroImage:
      "https://i.pinimg.com/736x/d6/19/06/d61906755efb4316c81d65d98e04948a.jpg",
    outfits: [
      {
        id: "outfit-4",
        name: "Executive Street",
        image: "https://i.pinimg.com/1200x/eb/03/67/eb0367217a73f126883c4c98526816db.jpg",
        totalPrice: 299.99,
        originalPrice: 359.99,
        items: ["Chaqueta Premium", "Camisa Urban", "Pantalón Formal", "Zapatos"],
      },
      {
        id: "outfit-5",
        name: "Weekend Luxury",
        image: "https://i.pinimg.com/736x/a7/8f/f2/a78ff29fc28317bf71a6b331f85c45fb.jpg",
        totalPrice: 249.99,
        items: ["Suéter Cashmere", "Jeans Premium", "Sneakers Limited"],
      },
    ],
  },
  {
    id: "seasonal-trends",
    name: "Tendencias de Temporada",
    description: "Los looks más actuales de la temporada",
    heroImage: "https://i.pinimg.com/1200x/18/2a/a6/182aa697ec1d980a5fc4ac24494b5a79.jpg",
    outfits: [
      {
        id: "outfit-6",
        name: "Spring Fresh",
        image: "https://i.pinimg.com/736x/83/20/29/8320290bc256aff738b85af1708fb4e0.jpg",
        totalPrice: 179.99,
        items: ["Camiseta Oversize", "Shorts Cargo", "Sneakers Colorful"],
      },
      {
        id: "outfit-7",
        name: "Summer Vibes",
        image: "https://i.pinimg.com/736x/0a/de/3b/0ade3b0550462117ee62e5bac035cc87.jpg",
        totalPrice: 139.99,
        originalPrice: 169.99,
        items: ["Tank Top", "Bermudas", "Sandalias Urban"],
      },
    ],
  },
]
